### ISSUE TITLE
E127: Cannot redefine function <SNR>64_Color: It is in use

### ISSUE THREAD

**Issue by BourgeoisBear** [bcicen/vim-vice#1]
On line 56 in vice.vim.

Installed plugins:
- CtrlP
- pathogen
- airline

VIM 7.4.576

**Comment by BourgeoisBear** [comment]
It works now, and I don't know why it didn't before.  Sorry for the interruption.

**Comment by bcicen** [comment]
closing for now; feel free to reopen if the issue resurfaces
