### ISSUE TITLE
Thanks for the colorscheme!

### ISSUE THREAD

**Issue by tonylambiris** [bcicen/vim-vice#8]
Just wanted to give you props for creating this awesome colorscheme! I use it on all my neovim installs and it's simply fantastic.

Also, I ported the colorscheme to gotop recently: https://github.com/cjbassi/gotop/pull/115

![53152625-0ce80c00-3584-11e9-8fbf-5aac8523adc5](https://user-images.githubusercontent.com/14058972/53689714-a1433300-3d29-11e9-8ad2-82f245c2f868.png)

I set an alias for it like so:
```
➜ alias gotop
gotop='gotop -c vice -f -p'
```

You can close this out anytime, thanks again!

**Comment by bcicen** [comment]
Looks great; thanks!

Added `gotop` to the [contrib section](https://github.com/bcicen/vim-vice#gotop).
